# Generated by Django 5.0.7 on 2024-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0003_userpreference_premium_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpreference',
            name='subscription_until',
            field=models.DateField(blank=True, null=True, verbose_name='Subscription Until'),
        ),
    ]
